server:
  port: 8888

spring:
  application:
    name: springCloudServer
  cloud:
    config:
     server:
       git:
         uri: file:/Users/kogayushi/Documents/workspace/spring-cloud-config-sample
         basedir: config-repo
         clone-on-start:  false
         force-pull: false
